// js/src/Brightness.jsx
import React, { useEffect, useState } from "react";
import { Box, Slider, Typography } from "@material-ui/core";
import axios from "axios";

export default function Brightness() {
  const [brightness, setBrightness] = useState(100);

  // Loads initial brightness once.
  useEffect(() => {
    axios.get("brightness").then((resp) => setBrightness(resp.data.data));
  }, []);

  const handleClick = (event, value) => {
    setBrightness(value);
  };

  const handleChange = async (event, value) => {
    await axios.post("brightness", { data: value });
  };

  return (
    <Box marginBottom={2}>
      <Typography gutterBottom>Brightness</Typography>
      <Slider
        value={brightness}
        onChange={handleClick}
        onChangeCommitted={handleChange}
        valueLabelDisplay="auto"
        min={0}
        max={100}
      />
    </Box>
  );
}

// web/sfrontend/src/Brightness.svelte
<script>
  import {onMount} from "svelte";

  let value = 100;

  onMount(async () => {
    const resp = await fetch("brightness");
    const data = await resp.json();
    value = data.value;
  });

  const handleChange = async (e, v) => {
    await fetch("brightness", {
      method: 'POST',
      data: {
        value: value,
      },
    });
  };
</script>

<div class="mb-2">
  <div>Brightness</div>
  <input
    type="range"
    min="0"
    max="100"
    bind:value
    on:change={handleChange}
  >
  <!-- valueLabelDisplay="auto" -->
</div>
