// web/frontend/src/ShowSelector.jsx
import React, { useEffect, useState } from "react";
import axios from "axios";
import {
  IconButton,
  List,
  ListItem,
  ListItemIcon,
  ListItemText,
  Typography,
} from "@material-ui/core";
import PlayCircleOutlineIcon from "@material-ui/icons/PlayCircleOutline";
import PlaylistAddIcon from "@material-ui/icons/PlaylistAdd";
import { addToPlaylist } from "./PlaylistActions";
import { useSetPlaylist } from "./PlaylistContext";

export default function ShowSelector() {
  const [shows, setShows] = useState([]);
  const setPlaylist = useSetPlaylist();

  useEffect(() => {
    // Get list of shows from server at startup.
    axios.get("shows").then((resp) => setShows(resp.data.shows));
  }, []);

  const clickPlay = async (show) => {
    await axios.post("shows", { value: show });
  };

  const clickEnqueue = async (show) => {
    await addToPlaylist(setPlaylist, show);
  };

  const PlayButton = ({ show }) => {
    return (
      <ListItemIcon>
        <IconButton onClick={() => clickPlay(show)}>
          <PlayCircleOutlineIcon />
        </IconButton>
      </ListItemIcon>
    );
  };

  const EnqueueButton = ({ show }) => {
    return (
      <ListItemIcon>
        <IconButton onClick={() => clickEnqueue(show)}>
          <PlaylistAddIcon />
        </IconButton>
      </ListItemIcon>
    );
  };

  return (
    <>
      <Typography variant="h5" gutterBottom>
        Show Selector
      </Typography>

      <List style={{ listStyle: "none" }} dense>
        {shows.map((show) => (
          <ListItem color="primary" divider>
            <ListItemText primary={show.name} secondary={show.description} />
            <PlayButton show={show.name} />
            <EnqueueButton show={show.name} />
          </ListItem>
        ))}
      </List>
    </>
  );
}

// web/sfrontend/src/ShowSelector.svelte
<script>
  import {onDestroy, onMount} from "svelte";
  import IconButton from '@smui/icon-button';
  import List, {Item, Text, PrimaryText, SecondaryText} from '@smui/list';
  import {addToPlaylist} from "./playlist_actions";

  let shows = [];

  const updateShowList = async () => {
    const resp = await fetch('shows');
    const data = await resp.json();
    shows = data.shows;
  };

  onMount(async () => {
    await updateShowList();
  });

  const interval = setInterval(updateShowList, 10_000);
  onDestroy(() => clearInterval(interval));

  const clickPlay = async (show) => {
    await fetch('shows', {
      method: 'POST',
      body: JSON.stringify({value: show}),
    });
  };

  const clickEnqueue = async (show) => {
    await addToPlaylist(show);
  }
</script>

<div class="mdc-typography--headline5">
  Show Selector
</div>

<List dense>
  {#each shows as show}
    <Item color="primary" divider>
      <Text>
        <PrimaryText>{show.name}</PrimaryText>
        <SecondaryText>{show.description}</SecondaryText>
      </Text>
      <IconButton on:click={() => clickPlay(show.name)}>play_circle</IconButton>
      <IconButton on:click={() => clickEnqueue(show.name)}>playlist_add</IconButton>
    </Item>
  {/each}
</List>
