// web/frontend/src/ShowCycle.jsx
import React, { useEffect, useState } from "react";
import axios from "axios";
import { Box, Slider, Typography } from "@material-ui/core";

export default function ShowCycle() {
  const [cycleSeconds, setCycleSeconds] = useState(60);

  // Loads initial cycleSeconds once.
  useEffect(() => {
    axios.get("cycle_time").then((resp) => setCycleSeconds(resp.data.value));
  }, []);

  const handleChange = (event, value) => {
    setCycleSeconds(value);
  };

  const handleChangeCommitted = async (event, value) => {
    await axios.post("cycle_time", { value: value });
  };

  return (
    <Box marginBottom={2}>
      <Typography gutterBottom>Show duration (s)</Typography>
      <Slider
        value={cycleSeconds}
        onChange={handleChange}
        onChangeCommitted={handleChangeCommitted}
        valueLabelDisplay="auto"
        step={10}
        marks
        min={10}
        max={120}
      />
    </Box>
  );
}

// web/sfrontend/src/ShowCycle.svelte
<script>
  import {onMount} from "svelte";

  let value = 60;

  onMount(async () => {
    const resp = await fetch("cycle_time");
    const data = await resp.json();
    value = data.value;
  });

  const handleChange = async (e, v) => {
    await fetch("cycle_time", {
      method: 'POST',
      data: {
        value: value,
      },
    });
  };
</script>

<div class="mb-2">
  <div>Show duration (s)</div>
  <input
    type="range"
    min="10"
    max="120"
    step="10"
    bind:value
    on:change={handleChange}
  >
  <!-- valueLabelDisplay="auto" -->
</div>
