// web/sfrontend/src/GlobalSettings.svelte
<script>
  import {Item, Text, Graphic} from '@smui/list';
</script>

<Item button onClick={handleClick}>
  <Text>
    <div class="mdc-typography--headline5">
      Global Settings
    </div>
  </Text>
  {#if open}
    <Graphic class="material-icons">expand_less</Graphic>
  {:else}
    <Graphic class="material-icons">expand_more</Graphic>
  {/if}
</Item>
  <Collapse in={open} timeout="auto">
    <Grid
      className={classes.grid}
      container
      direction="column"
      justify="center"
    >
      <Brightness />
      <ShowCycle />
      <Speed />
    </Grid>
  </Collapse>

// web/frontend/src/GlobalSettings.jsx
import React, { useState } from "react";
import {
  Collapse,
  ListItem,
  ListItemText,
  Grid,
  makeStyles,
  Typography,
} from "@material-ui/core";
import { ExpandLess, ExpandMore } from "@material-ui/icons";
import Brightness from "./Brightness";
import ShowCycle from "./ShowCycle";
import Speed from "./Speed";

const useStyles = makeStyles((theme) => ({
  grid: {
    padding: theme.spacing(2),
  },
}));

export default function GlobalSettings() {
  const classes = useStyles();
  const [open, setOpen] = useState(true);

  const handleClick = () => {
    setOpen(!open);
  };

  return (
    <>
      <ListItem button onClick={handleClick}>
        <ListItemText>
          <Typography variant="h5">Global Settings</Typography>
        </ListItemText>
        {open ? <ExpandLess /> : <ExpandMore />}
      </ListItem>
      <Collapse in={open} timeout="auto">
        <Grid
          className={classes.grid}
          container
          direction="column"
          justify="center"
        >
          <Brightness />
          <ShowCycle />
          <Speed />
        </Grid>
      </Collapse>
    </>
  );
}
