// web/sfrontend/src/Speed.svelte
<script>
  import {onMount} from "svelte";

  let value = 1.0;

  onMount(async () => {
    const resp = await fetch("speed");
    const data = await resp.json();
    value = data.value;
  });

  const handleChange = async (e, v) => {
    await fetch("speed", {
      method: 'POST',
      data: {
        value: value,
      },
    });
  };
</script>

<div class="mb-2">
  <div>Speed Multiplier (lower is faster)</div>
  <input
    type="range"
    min="0.5"
    max="2.0"
    step="0.25"
    bind:value
    on:change={handleChange}
  >
  <!-- valueLabelDisplay="auto" -->
</div>

// web/frontend/src/Speed.jsx
import React, { useEffect, useState } from "react";
import { Box, Slider, Typography } from "@material-ui/core";
import axios from "axios";

export default function Speed() {
  const [speed, setSpeed] = useState(1.0);

  // Load initial speed once.
  useEffect(() => {
    axios.get('speed').then((resp) => setSpeed(resp.data.value));
  }, []);

  const handleChange = (event, value) => {
    setSpeed(value);
  };

  const handleChangeCommitted = async (event, value) => {
    await axios.post('speed', {value: value});
  };

  return (
    <Box marginBottom={2}>
      <Typography gutterBottom>
        Speed Multiplier (lower is faster)
      </Typography>
      <Slider
        value={speed}
        onChange={handleChange}
        onChangeCommitted={handleChangeCommitted}
        valueLabelDisplay="auto"
        step={0.25}
        marks
        min={0.5}
        max={2.0}
      />
    </Box>
  );
};
